export const statesArray = [
  { fu: "AC", name: "Acre" },
  { fu: "AL", name: "Alagoas" },
  { fu: "AP", name: "Amapá" },
  { fu: "AM", name: "Amazonas" },
  { fu: "BA", name: "Bahia" },
  { fu: "CE", name: "Ceará" },
  { fu: "DF", name: "Distrito Federal" },
  { fu: "ES", name: "Espirito Santo" },
  { fu: "GO", name: "Goiás" },
  { fu: "MA", name: "Maranhão" },
  { fu: "MS", name: "Mato Grosso do Sul" },
  { fu: "MT", name: "Mato Grosso" },
  { fu: "MG", name: "Minas Gerais" },
  { fu: "PA", name: "Pará" },
  { fu: "PB", name: "Paraíba" },
  { fu: "PR", name: "Paraná" },
  { fu: "PE", name: "Pernambuco" },
  { fu: "PI", name: "Piauí" },
  { fu: "RJ", name: "Rio de Janeiro" },
  { fu: "RN", name: "Rio Grande do Norte" },
  { fu: "RS", name: "Rio Grande do Sul" },
  { fu: "RO", name: "Rondônia" },
  { fu: "RR", name: "Roraima" },
  { fu: "SC", name: "Santa Catarina" },
  { fu: "SP", name: "São Paulo" },
  { fu: "SE", name: "Sergipe" },
  { fu: "TO", name: "Tocantins" },
];
